name: 'demo_project'
version: '1.0.0'
config-version: 2

profile: 'demo_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  demo_project:
    # Config for all models
    materialized: table
